In [10]:
b=[]
n=int(input("Enter the size :"))
for i in range(n):
    x=int(input())
    b.append(x)
print(b)

Enter the size :10
1
2
3
4
5
6
7
8
9
10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
print(b[4:10])

[5, 6, 7, 8, 9, 10]


In [11]:
b.reverse()
#print(b)
b.remove(b[5])
print(b)

[10, 9, 8, 7, 6, 4, 3, 2, 1]


In [12]:
q=input("Enter any character :")
b.append(q)
print(b)

Enter any character :s
[10, 9, 8, 7, 6, 4, 3, 2, 1, 's']


In [14]:
s={4,6,9,8,12,1,3,5,4}
s

{1, 3, 4, 5, 6, 8, 9, 12}

In [15]:
s.update({12,34,56,35,67})
s

{1, 3, 4, 5, 6, 8, 9, 12, 34, 35, 56, 67}

In [16]:
d={4,6,9,8,12,1,3,5,4}
d.intersection(s)


{1, 3, 4, 5, 6, 8, 9, 12}

In [17]:
d.symmetric_difference(s)

{34, 35, 56, 67}

In [18]:
import numpy as n

In [28]:
s=n.array([6,5,7,9,2,4.0,"sd"])

In [29]:
s

array(['6', '5', '7', '9', '2', '4.0', 'sd'], dtype='<U32')

In [30]:
s.dtype

dtype('<U32')

In [31]:
s=n.arange(2,4)

In [32]:
s

array([2, 3])

In [36]:
s.sum

<function ndarray.sum>

In [41]:
import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]).reshape(5,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [55]:
print(a1[2:5,1:4])


[[10 11 12]
 [14 15 16]
 [18 19 20]]


In [56]:
a1[2:5,1:4]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [60]:
a1[0:3,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])